# fly.toml app configuration file generated for basic-sparkling-thunder-7964 on 2025-02-19T10:46:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml — low-cost, instantly-available in GIG & MIA

app = "basic-sparkling-thunder-7964"
primary_region = "mia"          # pick one; MIA is a good primary for the US/East

[regions]
serve = ["gig", "mia"]

[build]

  [build.args]
  REACT_APP_API_BASE_URL = "https://backend-weathered-shadow-9057.fly.dev"
  REACT_APP_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmstaGVyb2ljLWRvZy04MS5jbGVyay5hY2NvdW50cy5kZXYk"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false    # keep one warm per region for "instant" availability
  min_machines_running = 1      # per region (for regions you place machines in)
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"           # or "connections" for websockets
    soft_limit = 100
    hard_limit = 200

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512               # smallest RAM for lowest cost


