app = 'backend-weathered-shadow-9057'
primary_region = "mia"          # pick one; MIA is a good primary for the US/East

[regions]
serve = ["gig", "mia"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false    # keep one warm per region for "instant" availability
  min_machines_running = 1      # per region (for regions you place machines in)

  [http_service.concurrency]
    type = "requests"           # or "connections" for websockets
    soft_limit = 100
    hard_limit = 200

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
