"""add_shares_outstanding_to_companies

Revision ID: 57d8fcda632a
Revises: 8472341b0647
Create Date: 2025-07-20 14:25:40.460104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# gitleaks:disable
revision: str = '57d8fcda632a' #pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = '8472341b0647' #pragma: allowlist secret
# gitleaks:enable
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('shares_outstanding', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'shares_outstanding')
    # ### end Alembic commands ###
