"""add company table

Revision ID: bf8c043bf4dd
Revises:
Create Date: 2025-07-20 11:27:28.212734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import adapters.orm


# revision identifiers, used by Alembic.
# gitleaks:disable
revision: str = 'bf8c043bf4dd' #pragma: allowlist secret
# gitleaks:enable
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', adapters.orm.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('cusip', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('is_delisted', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('sic', sa.String(), nullable=True),
    sa.Column('sic_sector', sa.String(), nullable=True),
    sa.Column('sic_industry', sa.String(), nullable=True),
    sa.Column('fama_sector', sa.String(), nullable=True),
    sa.Column('fama_industry', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('sec_api_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sec_api_id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('significant_moves',
    sa.Column('id', adapters.orm.GUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pct_change', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('catalyst', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_significant_moves_ticker_date', 'significant_moves', ['ticker', 'occurred_at'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', adapters.orm.GUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('market_reference_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_prices_ticker_date', 'stock_prices', ['ticker', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_prices_ticker_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index('ix_significant_moves_ticker_date', table_name='significant_moves')
    op.drop_table('significant_moves')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
